# -*- coding: utf-8 -*-
"""Counelling_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mreD5gHh9O6TIT8YYLZtVvfqSfvyT_w9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc
import subprocess
import sys


df=pd.read_excel("/content/Copy of cleaned_josaa_data_(1)(1).xlsx")
df.info()

# Define target variable: Admission status
threshold = 10000  # Example: Consider closing rank <= 10000 as admitted
df['admission_status'] = (df['closing_rank'] <= threshold).astype(int)

# Drop unnecessary columns (year, round are not useful for prediction)
df.drop(columns=['year', 'round'], inplace=True)

categorical_columns = ['institute', 'academic_program_name', 'quota', 'seat_type', 'gender']
label_encoders = {}
for col in categorical_columns:
    label_encoders[col] = LabelEncoder()
    df[col] = label_encoders[col].fit_transform(df[col])

# Define features (X) and target (y)
X = df.drop(columns=['closing_rank', 'admission_status'])  # Exclude closing_rank from features
y = df['admission_status']

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train Logistic Regression Model
model_lr = LogisticRegression(max_iter=1000)
model_lr.fit(X_train, y_train)
y_pred_lr = model_lr.predict(X_test)
y_proba_lr = model_lr.predict_proba(X_test)[:, 1]

# Train Random Forest Model
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)
y_pred_rf = model_rf.predict(X_test)
y_proba_rf = model_rf.predict_proba(X_test)[:, 1]

# Train Support Vector Classifier (SVC) Model
model_svc = SVC(kernel='rbf', probability=True, random_state=42)
model_svc.fit(X_train, y_train)
y_pred_svc = model_svc.predict(X_test)
y_proba_svc = model_svc.predict_proba(X_test)[:, 1]

# Evaluate Models
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))

print("SVC Accuracy:", accuracy_score(y_test, y_pred_svc))
print(classification_report(y_test, y_pred_svc))

# Confusion Matrix
plt.figure(figsize=(6,6))
sns.heatmap(confusion_matrix(y_test, y_pred_svc), annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("SVC Confusion Matrix")
plt.show()

# ROC Curve
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_proba_lr)
roc_auc_lr = auc(fpr_lr, tpr_lr)

fpr_rf, tpr_rf, _ = roc_curve(y_test, y_proba_rf)
roc_auc_rf = auc(fpr_rf, tpr_rf)

fpr_svc, tpr_svc, _ = roc_curve(y_test, y_proba_svc)
roc_auc_svc = auc(fpr_svc, tpr_svc)

plt.figure(figsize=(8,6))
plt.plot(fpr_lr, tpr_lr, color='blue', lw=2, label=f'LR ROC (AUC = {roc_auc_lr:.2f})')
plt.plot(fpr_rf, tpr_rf, color='red', lw=2, label=f'RF ROC (AUC = {roc_auc_rf:.2f})')
plt.plot(fpr_svc, tpr_svc, color='green', lw=2, label=f'SVC ROC (AUC = {roc_auc_svc:.2f})')
plt.plot([0,1], [0,1], linestyle='--', color='gray')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
plt.legend()
plt.show()

subprocess.check_call([sys.executable, "-m", "pip", "install", "eli5"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "shap"])
subprocess.check_call([sys.executable, "-m", "pip", "install", "lime"])


from lime.lime_tabular import LimeTabularExplainer

# Create LIME explainer
explainer = LimeTabularExplainer(
    training_data=X_train.values,
    feature_names=X.columns.tolist(),
    class_names=['Not Admitted', 'Admitted'],
    mode='classification'
)

# Choose one instance to explain
instance_index = 0  # you can change this
exp = explainer.explain_instance(
    data_row=X_test.values[instance_index],
    predict_fn=model_svc.predict_proba
)

# Show in notebook
exp.show_in_notebook(show_table=True)

from sklearn.inspection import permutation_importance
import pandas as pd
import matplotlib.pyplot as plt

# Calculate permutation importance
perm_result = permutation_importance(model_svc, X_test, y_test, n_repeats=10, random_state=42)

# Create a DataFrame to display feature importance
importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': perm_result.importances_mean
}).sort_values(by='Importance', ascending=False)

# Print top features
print(importance_df.head(10))

plt.figure(figsize=(10, 6))
plt.barh(importance_df['Feature'], importance_df['Importance'])
plt.xlabel("Importance Score")
plt.title("Permutation Feature Importance (SVM)")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

def final_model_predict(X):
    """
    Given input features X, predicts the class using an ensemble
    of Logistic Regression, Random Forest, and SVC with weights 25:50:25.

    Parameters:
        X (DataFrame or array-like): The input features in the same format as used for training.

    Returns:
        final_pred (ndarray): Final predicted class labels (0 or 1).
        weighted_proba (ndarray): Final weighted probability of the positive class.
    """
    # Get probability predictions for the positive class from each model
    proba_lr = model_lr.predict_proba(X)[:, 1]
    proba_rf = model_rf.predict_proba(X)[:, 1]
    proba_svc = model_svc.predict_proba(X)[:, 1]

    # Compute weighted average of the probabilities using the ratio 0.25, 0.50, 0.25
    weighted_proba = (0.25 * proba_lr) + (0.50 * proba_rf) + (0.25 * proba_svc)

    # Convert weighted probability to final prediction using threshold of 0.5
    final_pred = (weighted_proba >= 0.5).astype(int)

    return final_pred, weighted_proba

# Example usage:
# X_sample can be one or more observations in the same format as X_test.
X_sample = X_test.iloc[:5]  # for demonstration, using the first 5 test samples
predictions, probabilities = final_model_predict(X_sample)
print("Ensemble Predictions:", predictions)
print("Ensemble Probabilities:", probabilities)

import pandas as pd

# ---------- Manual Input for Custom Prediction ----------
print("Please enter the following details for your custom input:")

# Prompt the user to input all features that were used during training.
# Remove year and round from input
#year = int(input("Enter Admission Year (e.g., 2023): "))
#round_number = int(input("Enter Round Number (e.g., 6): "))
institute = input("Enter Institute Name (e.g., Indian Institute of Technology Bhubaneswar): ")
academic_program_name = input("Enter Academic Program Name (e.g., Civil Engineering (4 Years, Bachelor of Technology)): ")
quota = input("Enter Quota (e.g., AI): ")
seat_type = input("Enter Seat Type (e.g., OPEN): ")
gender = input("Enter Gender (e.g., Gender-Neutral): ")
opening_rank = int(input("Enter Opening Rank (e.g., 9500): "))

# Create a dictionary with the features in the correct order as used in training.
# Remove year and round from feature_columns
feature_columns = ["institute", "academic_program_name", "quota", "seat_type", "gender", "opening_rank"]
custom_input = {
    #"year": year,
    #"round": round_number,
    "institute": institute,
    "academic_program_name": academic_program_name,
    "quota": quota,
    "seat_type": seat_type,
    "gender": gender,
    "opening_rank": opening_rank
}

# Convert the dictionary into a DataFrame with the same column order as in the training data.
input_df = pd.DataFrame([custom_input], columns=feature_columns)

# If any preprocessing (e.g., encoding of categorical features) was applied during training,
# apply the same transformations here. For example:
# Apply the same Label Encoding used during training
for col in ['institute', 'academic_program_name', 'quota', 'seat_type', 'gender']:
    input_df[col] = label_encoders[col].transform(input_df[col])


# ---------- Make Prediction Using the Final Ensemble Model ----------
predicted_class, weighted_probability = final_model_predict(input_df)

# ---------- Output the Prediction ----------
print("\n✅ Final Ensemble Model Prediction:")
print("Predicted Admission Status (0=Rejected, 1=Accepted):", predicted_class[0])
print("Weighted Probability for Positive Class:", weighted_probability[0])